<a href="https://colab.research.google.com/github/Sid2996/sid/blob/python/numpy27july2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([11,22,33,44,55,66,77])
print(a.shape,a.ndim,a.size)

(7,) 1 7


In [ ]:
a=np.array([[11,22,33],[44,55,66,77]])
print(a.shape,a.ndim,a.size)

(2,) 1 2


In [ ]:
a=np.array([[[11,22,33],[44,55,66,77]]])
print(a.shape,a.ndim,a.size)

(1, 2) 2 2


In [ ]:
a=np.array([[10,20,30,33],[40,45,50,55],[70,80,90,100]])
print(a.shape,a.ndim,a.size)#shape only gives when square else only rows
#dim only gives what shape registered
#size rows registered by shape  
for i in a:
  print("data--->",i)

a[2][2]

(3, 4) 2 12
data---> [10 20 30 33]
data---> [40 45 50 55]
data---> [ 70  80  90 100]


90

In [ ]:
print(a[0:2,0:2])

[[10 20]
 [40 45]]


In [ ]:
a=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(a)
a[0:3,1:3]


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


array([[ 20,  30],
       [ 60,  70],
       [100, 110]])

In [ ]:
a=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(a)
print("TRanspose:\n",a.T)#transpose
print("in to 2:\n",a*2)#scalar multiplication



[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
TRanspose:
 [[ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]
 [ 40  80 120]]
in to 2:
 [[ 20  40  60  80]
 [100 120 140 160]
 [180 200 220 240]]


In [ ]:
a=np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
a=np.arange(10,110,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
a=np.arange(100,0,-10)
print(a)

[100  90  80  70  60  50  40  30  20  10]


In [ ]:
a=np.arange(1,13)
print(a)
a2=a.reshape(3,4)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.arange(0,17,2)
print(a)
a2=a.reshape(3,3)
print(a2)


[ 0  2  4  6  8 10 12 14 16]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [ ]:
a2=np.arange(10,170,10)
print(a2)
a3=a2.reshape(4,4)
print(a3)
a3[1:3,1:3]


[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


array([[ 60,  70],
       [100, 110]])

In [ ]:
a=np.arange(1,11)
print(a)
a2=np.linspace(10,100,4)#start to end given number of parts equal divide
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10.  40.  70. 100.]


In [ ]:
a=np.arange(1,11)
print(a)
aans=np.where(a%2==0)
print(aans)

[ 1  2  3  4  5  6  7  8  9 10]
(array([1, 3, 5, 7, 9]),)


In [ ]:
a=np.array([[5,10,15,38,12,30,7]])
print(a)
b=a.mean()
print(b)
aans=np.where(a>a.mean())
print(a[aans])


[[ 5 10 15 38 12 30  7]]
16.714285714285715
[38 30]


In [ ]:
#import random
from numpy import random


In [ ]:
random.randint(1,20,size=(10))#only for int

array([ 6, 17,  7,  5,  5, 15,  1,  8,  3, 11])

In [ ]:
random.rand(100)

array([0.52431627, 0.12664793, 0.55996506, 0.56343144, 0.55858796,
       0.46408228, 0.38101253, 0.064472  , 0.19369486, 0.92365246,
       0.59630687, 0.63303456, 0.32675098, 0.78015269, 0.19775271,
       0.14230943, 0.17422319, 0.72958553, 0.39988403, 0.21592479,
       0.88863368, 0.48262544, 0.76334875, 0.45546632, 0.28701977,
       0.89391425, 0.38303251, 0.3036724 , 0.20235209, 0.55222389,
       0.33396128, 0.88066236, 0.65507104, 0.05432474, 0.09731837,
       0.97223941, 0.4105122 , 0.57819115, 0.12298658, 0.77313443,
       0.33801369, 0.48271039, 0.60141627, 0.62200262, 0.0476901 ,
       0.72316239, 0.96131938, 0.59215277, 0.70155919, 0.60964203,
       0.07130268, 0.50080798, 0.17170927, 0.66772897, 0.97225515,
       0.8995565 , 0.6871803 , 0.4087122 , 0.8796105 , 0.38898778,
       0.85926663, 0.15807171, 0.34646686, 0.4246611 , 0.40036439,
       0.47349778, 0.47616176, 0.81328729, 0.71291147, 0.18968682,
       0.85249197, 0.74435936, 0.37217992, 0.77536124, 0.50978

In [ ]:
color=random.choice(["red","silver","white","blue","black"])
print("You got:",color)

You got: red


In [ ]:
from numpy import random
a=random.randint(1,100,size=(25))
a.reshape(5,5)


array([[33, 77, 81, 30, 63],
       [71, 64,  2, 93,  1],
       [48, 72, 35, 75, 35],
       [80, 19, 81, 23, 20],
       [37, 84, 18, 50, 87]])

[3 2]
